Draft: simulation endpoint that retains state
EnsoFinance/transaction-simulator pull request #9
Opened 2023-06-21 16:58 UTC by ape-dev-cs

2023-06-22 11:14 UTC, devanoneth requested changes
Thanks for this ser, really nice! 👑 On the CI, if you pull in the latest changes to `main`, it should work now. RPC was timing out.

Could you also update the README with details on these new endpoints? Thanks!

2023-06-22 11:14 UTC, devanoneth commented on src/lib.rs
> +/// POST /simulate-stateful-new
```suggestion
/// POST /simulate-stateful
```

Would prefer just a POST without an id to setup your state. Would be more RESTful then.

2023-06-22 11:14 UTC, devanoneth commented on src/lib.rs
> +    warp::path!("simulate-stateful-new")
```suggestion
    warp::path!("simulate-stateful")
```

2023-06-22 11:14 UTC, devanoneth commented on src/simulation.rs
> +    pub stateful_simulation_id: u32,
I think UUIDs could be nicer than an incrementing id int. It means that if in future we allow a DB to be hooked up and multiple simulators to be run, the API doesn't need to change. I also frankly think the URLs will look nicer. :D  What do you think?

2023-06-22 20:12 UTC, merged

2023-06-22 20:12 UTC, devanoneth commented
Thanks for the contribution!

2023-06-22 20:16 UTC, ConnorSB13 commented
Thanks Mr Ape!

2023-06-26 19:19 UTC, polyphia commented
Amazing !